# Site settings
title: Foodz
email: leeann.drees@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Food I made/ate that I liked.
baseurl: "/foodz" # the subpath of your site, e.g. /blog/
url: "http://leeanndrees.github.io" # the base hostname & protocol for your site
twitter_username: leeanndrees
github_username:  leeanndrees

# Build settings
markdown: kramdown
